apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm64-spot
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t4g.large", "m6g.large", "c6g.large"]
      nodeClassRef:
        name: default
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: "${module.eks.eks_managed_node_groups["initial"].iam_role_name}"
  subnetSelectorTerms:
    - tags:
        "karpenter.sh/discovery": "${var.cluster_name}"
  securityGroupSelectorTerms:
    - tags:
        "karpenter.sh/discovery": "${var.cluster_name}"